(part "REF3440TIDBVR"
    (packageRef "SOT95P280X145-6N")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-REF3440TIDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/REF3440TIDBVR?qs=aP1CjGhiNiFrJEFwygVNiw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "REF3440TIDBVR")
    (property "Description" "Voltage References 4.1-V, low-drift, low-power, small-footprint series voltage reference")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/ref3425.pdf?ts=1626722188647")
    (property "symbolName1" "REF3440TIDBVR")
)
